import org.jetbrains.compose.desktop.application.dsl.TargetFormat
import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.androidMultiplatformLibrary)
    alias(libs.plugins.composeMultiplatform)
    alias(libs.plugins.composeCompiler)
    alias(libs.plugins.kotlinxSerialization)
}

val appVersionName = providers.gradleProperty("ohmysshVersionName").getOrElse("0.0.0")

// A git tag is free-form text on its way into a Kotlin string literal, so a
// stray quote, backslash or dollar in one must not break the build.
val appReleaseTag = providers.gradleProperty("ohmysshReleaseTag").getOrElse("")
    .filter { it.isLetterOrDigit() || it in "-._+" }

// The version the app shows in Settings comes from here, so a tagged CI build
// reports the tag rather than whatever gradle.properties last held.
val generateBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildInfo/kotlin")
    inputs.property("versionName", appVersionName)
    inputs.property("releaseTag", appReleaseTag)
    outputs.dir(outputDir)
    doLast {
        val dir = outputDir.get().asFile.resolve("com/example/ohmyssh/platform")
        dir.mkdirs()
        dir.resolve("BuildInfo.kt").writeText(
            """
            // Generated by :shared:generateBuildInfo. Edit ohmysshVersionName in
            // gradle.properties, not this file.
            package com.example.ohmyssh.platform

            const val appVersion: String = "$appVersionName"

            fun releaseTag(): String = "$appReleaseTag"
            """.trimIndent() + "\n",
        )
    }
}

kotlin {
    // Manual dependsOn edges (jvmShared) suppress the default template, so it
    // is applied explicitly to keep iosMain and friends.
    applyDefaultHierarchyTemplate()

    androidLibrary {
        namespace = "com.example.ohmyssh.shared"
        compileSdk = libs.versions.android.compileSdk.get().toInt()
        minSdk = libs.versions.android.minSdk.get().toInt()

        compilerOptions {
            jvmTarget = JvmTarget.JVM_11
        }
        androidResources {
            enable = true
        }
    }

    jvm("desktop")

    listOf(
        iosArm64(),
        iosSimulatorArm64(),
    ).forEach { iosTarget ->
        iosTarget.binaries.framework {
            baseName = "Shared"
            isStatic = true
        }
    }

    sourceSets {
        val commonMain by getting {
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                implementation(compose.runtime)
                implementation(compose.foundation)
                implementation(compose.material3)
                implementation(compose.ui)
                implementation(compose.components.resources)
                implementation(libs.compose.material.icons.core)
                implementation(libs.compose.material.icons.extended)
                implementation(libs.kotlinx.coroutines.core)
                implementation(libs.kotlinx.serialization.json)
                implementation(libs.cryptography.core)
                implementation(libs.multiplatform.settings)
                implementation(libs.filekit.core)
            }
        }

        val jvmShared by creating {
            dependsOn(commonMain)
            dependencies {
                implementation(libs.sshj)
                implementation(libs.slf4j.nop)
                implementation(libs.cryptography.provider.jdk)
            }
        }

        val androidMain by getting {
            dependsOn(jvmShared)
            dependencies {
                implementation(libs.androidx.activity.compose)
                implementation(libs.usb.serial.android)
                implementation(libs.bouncycastle.provider)
            }
        }

        val desktopMain by getting {
            dependsOn(jvmShared)
            dependencies {
                implementation(compose.desktop.currentOs)
                implementation(libs.kotlinx.coroutines.swing)
                implementation(libs.jserialcomm)
                implementation(libs.jna)
            }
        }

        val iosMain by getting {
            dependencies {
                implementation(libs.cryptography.provider.openssl3)
            }
        }

        val desktopTest by getting {
            dependencies {
                implementation(kotlin("test"))
                implementation(libs.kotlinx.coroutines.core)
            }
        }
    }
}

// The MCP server ships as one jar so an MCP client can launch it with a plain
// `java -cp`. The uber jar merges signed dependency jars (BouncyCastle), and the
// JVM refuses to load classes from the result — "Invalid signature file digest
// for Manifest main attributes" — until their signature files are dropped.
val mcpJar by tasks.registering {
    dependsOn("packageUberJarForCurrentOS")
    val jarsDir = layout.buildDirectory.dir("compose/jars")
    outputs.upToDateWhen { false }
    doLast {
        val jar = jarsDir.get().asFile.listFiles { file -> file.name.endsWith(".jar") }
            ?.maxByOrNull { it.lastModified() }
            ?: error("packageUberJarForCurrentOS produced no jar")
        val strip = ProcessBuilder(
            "zip", "-q", "-d", jar.absolutePath,
            "META-INF/*.SF", "META-INF/*.DSA", "META-INF/*.RSA",
        ).redirectErrorStream(true).start()
        val output = strip.inputStream.readBytes().decodeToString()
        // zip exits 12 when it finds nothing to delete, which is the normal case
        // on a jar that has already been stripped.
        val code = strip.waitFor()
        if (code != 0 && code != 12) error("stripping signatures failed ($code): $output")
        logger.lifecycle("MCP server jar: ${jar.absolutePath}")
    }
}

compose.desktop {
    application {
        mainClass = "com.example.ohmyssh.MainKt"

        nativeDistributions {
            targetFormats(TargetFormat.Dmg, TargetFormat.Msi, TargetFormat.Deb)
            packageName = "ohmyssh"
            packageVersion = appVersionName
            description = "Simple, reliable SSH/SFTP client"
            // sshj and the JDK crypto provider load ciphers reflectively, so a
            // jlink image trimmed to the modules the compiler saw drops key
            // exchange algorithms at runtime.
            includeAllModules = true
            // Regenerate all three with artwork/generate-app-icons.py; jpackage
            // wants a per-platform container and rejects a bare PNG on mac/Windows.
            macOS {
                bundleID = "com.example.ohmyssh"
                iconFile.set(rootProject.file("artwork/desktop/app-icon-macos.icns"))
            }
            windows { iconFile.set(rootProject.file("artwork/desktop/app-icon-windows.ico")) }
            linux { iconFile.set(rootProject.file("artwork/desktop/app-icon-linux.png")) }
        }
    }
}
